name: insta_flutter_fire
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^4.0.0
  cloud_firestore: ^3.1.13
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.15
  firebase_core: ^1.15.0
  firebase_storage: ^10.2.13
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.3
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.0.1
  hooks_riverpod: ^1.0.3
  image_picker: ^0.8.5
  logger: 
    git: https://github.com/LuckUVeryX/logger.git
  mockito: ^5.1.0


dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.10
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2
  json_serializable: ^6.2.0


flutter:
  uses-material-design: true

  assets:
      - assets/svg/